#!/usr/bin/env node
/*
 * configure.js — Safety Lab Aero self-hosted config generator. (10 Sep 2026)
 *
 * Turns a short answers file into the `slab_env.js` the app loads FIRST, so a
 * customer never hand-edits window.__SLAB_* globals. It validates BEFORE it
 * writes, mirroring the startup hard-stop in site/slab_config.js — most
 * importantly the trap where a blank AI endpoint in self-hosted mode would fall
 * back to Safety Lab's proxy and leak. Catch it here, not at boot.
 *
 * Run:  node configure.js [answers.env] [slab_env.js]
 *   answers.env defaults to ./install.env ; output defaults to ./slab_env.js
 */
'use strict';

var OUR_DB_HOST = 'fhrqkhdrwbfnizkepkch.supabase.co';

function trim(u) { return (u == null ? '' : String(u)).replace(/\/+$/, ''); }
function hostOf(u) { try { return new URL(u).host.toLowerCase(); } catch (_) { return ''; } }
function validUrl(u) { try { new URL(u); return true; } catch (_) { return false; } }
function pointsAtSafetyLab(u) {
  if (!u) return false;
  var h = hostOf(u);
  return h === OUR_DB_HOST || /(^|\.)safetylabaero\.com$/.test(h);
}

// Pure core: answers -> { ok, errors, warnings, file }. Tested by the wall.
function buildConfig(answers) {
  answers = answers || {};
  var mode = (answers.mode || 'self-hosted').trim();
  var dbUrl = trim(answers.dbUrl);
  var dbKey = (answers.dbKey == null ? '' : String(answers.dbKey)).trim();
  var aiEndpoint = trim(answers.aiEndpoint);
  var webAppUrl = trim(answers.webAppUrl);
  var corpusEndpoint = trim(answers.corpusEndpoint);
  var aiOff = answers.aiOff === true || String(answers.aiOff).toLowerCase() === 'true';

  var errors = [], warnings = [];
  var SL = ' points at Safety Lab — a customer install must never reach Safety Lab. Use your own address.';

  if (mode === 'self-hosted') {
    if (!dbUrl) errors.push('Database URL is required for a self-hosted install.');
    else if (!validUrl(dbUrl)) errors.push('Database URL is not a valid web address: ' + dbUrl);
    else if (pointsAtSafetyLab(dbUrl)) errors.push('Database URL (' + hostOf(dbUrl) + ')' + SL);
    if (!dbKey) errors.push('Database key is required.');

    if (aiOff) {
      if (aiEndpoint) warnings.push('AI is switched off, so the AI endpoint you gave will be ignored.');
    } else if (!aiEndpoint) {
      errors.push('AI endpoint is required (or set AI_OFF=true). A blank AI endpoint would fall back to Safety Lab and leak your data.');
    } else if (!validUrl(aiEndpoint)) {
      errors.push('AI endpoint is not a valid web address: ' + aiEndpoint);
    } else if (pointsAtSafetyLab(aiEndpoint)) {
      errors.push('AI endpoint (' + hostOf(aiEndpoint) + ')' + SL);
    }

    if (webAppUrl && pointsAtSafetyLab(webAppUrl)) errors.push('Web address (' + hostOf(webAppUrl) + ')' + SL);
    if (corpusEndpoint && pointsAtSafetyLab(corpusEndpoint)) errors.push('Method-corpus endpoint (' + hostOf(corpusEndpoint) + ')' + SL);
  } else if (mode === 'browser-only') {
    var strays = [];
    if (dbUrl) strays.push('database URL');
    if (dbKey) strays.push('database key');
    if (corpusEndpoint) strays.push('method-corpus endpoint');
    if (webAppUrl) strays.push('web address');
    if (strays.length) errors.push('A browser-only install keeps everything on the machine, so it must have no backend settings — but these were set: ' + strays.join(', ') + '.');
    if (!aiOff && aiEndpoint && pointsAtSafetyLab(aiEndpoint)) errors.push('AI endpoint (' + hostOf(aiEndpoint) + ')' + SL);
  } else {
    errors.push('Unknown MODE "' + mode + '". Use self-hosted or browser-only.');
  }

  var lines = [];
  lines.push('/* Safety Lab Aero — install configuration. Generated by configure.js on ' + new Date().toISOString().slice(0, 10) + '.');
  lines.push(' * Load this BEFORE the app scripts:  <script src="slab_env.js"></script>');
  lines.push(' * Mode: ' + mode + '. This file names only YOUR addresses — nothing points at Safety Lab. */');
  lines.push('(function (w) {');
  if (mode === 'browser-only') {
    lines.push('  w.__SLAB_LOCAL_ONLY__ = true;');
    if (aiOff) lines.push('  w.__SLAB_AI_OFF__ = true;');
    else if (aiEndpoint) lines.push('  w.__SLAB_AI_ENDPOINT__ = ' + JSON.stringify(aiEndpoint) + ';');
  } else if (mode === 'self-hosted') {
    lines.push('  w.__SLAB_SUPABASE_URL__ = ' + JSON.stringify(dbUrl) + ';');
    lines.push('  w.__SLAB_SUPABASE_KEY__ = ' + JSON.stringify(dbKey) + ';');
    if (aiOff) lines.push('  w.__SLAB_AI_OFF__ = true;');
    else lines.push('  w.__SLAB_AI_ENDPOINT__ = ' + JSON.stringify(aiEndpoint) + ';');
    if (webAppUrl) lines.push('  w.__SLAB_WEB_APP_URL__ = ' + JSON.stringify(webAppUrl) + ';');
    if (corpusEndpoint) lines.push('  w.__SLAB_CORPUS_ENDPOINT__ = ' + JSON.stringify(corpusEndpoint) + ';');
  }
  lines.push('})(window);');
  lines.push('');

  return { ok: errors.length === 0, errors: errors, warnings: warnings, file: lines.join('\n'), mode: mode };
}

function parseEnv(text) {
  var out = {};
  String(text).split(/\r?\n/).forEach(function (raw) {
    var line = raw.trim();
    if (!line || line[0] === '#') return;
    var eq = line.indexOf('=');
    if (eq < 0) return;
    var k = line.slice(0, eq).trim();
    var v = line.slice(eq + 1).trim().replace(/^["']|["']$/g, '');
    out[k] = v;
  });
  return {
    mode: out.MODE, dbUrl: out.DB_URL, dbKey: out.DB_KEY, aiEndpoint: out.AI_ENDPOINT,
    webAppUrl: out.WEB_APP_URL, corpusEndpoint: out.CORPUS_ENDPOINT, aiOff: out.AI_OFF
  };
}

module.exports = { buildConfig: buildConfig, parseEnv: parseEnv, pointsAtSafetyLab: pointsAtSafetyLab };

// ---- CLI ----
if (require.main === module) {
  var fs = require('fs'), path = require('path');
  var inFile = process.argv[2] || 'install.env';
  var outFile = process.argv[3] || 'slab_env.js';
  if (!fs.existsSync(inFile)) {
    console.error('No answers file found at ' + inFile + '. Copy install.env.example to install.env and fill it in.');
    process.exit(1);
  }
  var res = buildConfig(parseEnv(fs.readFileSync(inFile, 'utf8')));
  res.warnings.forEach(function (w) { console.log('  !  ' + w); });
  if (!res.ok) {
    console.error('\nConfiguration NOT written — fix these first:\n');
    res.errors.forEach(function (e) { console.error('  x  ' + e); });
    console.error('');
    process.exit(1);
  }
  fs.writeFileSync(outFile, res.file);
  console.log('\n  ok  Wrote ' + path.resolve(outFile) + ' (mode: ' + res.mode + ').');
  console.log('      Include it before the app scripts, then open the app and run  SLConfigEgress()  in the console');
  console.log('      to confirm nothing points at Safety Lab. Then run ./verify.sh to check the database.');
  process.exit(0);
}
