#!/usr/bin/env node
// tools/seo/footer.mjs — ONE footer for every marketing page (23 Sep 2026, SEO read, items 2 and 6).
//
// WHY: the site had become two islands. The five topic pages shared one footer that linked only to
// each other; the calculators, templates, ROI, trust, AI-guardrails and legal pages each had a
// footer of their own that linked back to the homepage and nowhere else. The homepage footer did
// not link to three of the five topic pages at all. Search engines pass authority along links, so
// the pages meant to rank were the ones getting the least of it. This script writes the same
// footer into every page between two markers, and `--check` fails the wall if any page drifts.
//
//   node tools/seo/footer.mjs            rewrite the footer block in every listed page
//   node tools/seo/footer.mjs --check    exit 1 if any page's block differs from the template
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..");
const SITE = path.join(ROOT, "site");
const BEGIN = "<!-- SITE-FOOTER:BEGIN (generated by tools/seo/footer.mjs, do not hand-edit) -->";
const END = "<!-- SITE-FOOTER:END -->";

// landing.html keeps its own footer (different layout); everything else carries this one.
export const PAGES = [
  "fault-tree-analysis.html", "functional-hazard-assessment.html", "arp-4761a.html", "arp-4754b.html",
  "fmea-software.html", "common-cause-analysis.html", "medini-analyze-alternative.html", "resources.html",
  "roi.html", "tools.html", "templates.html", "ai-guardrails.html", "trust.html", "legal.html", "privacy.html", "404.html",
];

export const LINKS = {
  Product: [
    ["/fault-tree-analysis", "Fault tree analysis"],
    ["/functional-hazard-assessment", "Functional hazard assessment"],
    ["/arp-4761a", "ARP 4761A process"],
    ["/arp-4754b", "ARP 4754B and DAL allocation"],
    ["/fmea-software", "FMEA"],
    ["/common-cause-analysis", "CMA, PRA and ZSA"],
  ],
  Resources: [
    ["/resources", "Guides"],
    ["/tools", "Free calculators"],
    ["/templates", "Free templates"],
    ["/roi", "ROI calculator"],
    ["/medini-analyze-alternative", "Medini Analyze alternative"],
  ],
  Company: [
    ["/trust", "Trust and security"],
    ["/ai-guardrails", "AI guardrails"],
    ["/#pricing", "Pricing"],
    ["/#about", "About"],
    ["mailto:waqas.nafees@safetylabaero.com", "Contact"],
    ["/app", "Sign in"],
  ],
  Legal: [
    ["/legal", "License agreement"],
    ["/privacy", "Privacy policy"],
  ],
};

export function render() {
  const cols = Object.entries(LINKS).map(([h, links]) =>
    `    <div class="sf-col"><span class="sf-h">${h}</span>${links.map(([u, t]) => `<a href="${u}">${t}</a>`).join("")}</div>`).join("\n");
  return [
    BEGIN,
    `<footer class="sf" aria-label="Site footer">`,
    `<style>.sf{margin-top:56px;padding:28px 0 22px;border-top:1px solid rgba(128,128,128,.28);font-size:14px;line-height:1.7}.sf-in{max-width:1080px;margin:0 auto;padding:0 24px;display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:18px 28px}.sf-col{display:flex;flex-direction:column}.sf-h{font-weight:700;margin-bottom:4px}.sf a{color:inherit;opacity:.82;text-decoration:none}.sf a:hover{opacity:1;text-decoration:underline}.sf-copy{max-width:1080px;margin:22px auto 0;padding:0 24px;font-size:13px;opacity:.75}</style>`,
    `  <div class="sf-in">`,
    cols,
    `  </div>`,
    `  <p class="sf-copy">&copy; 2026 Safety Lab Aero, Inc. &middot; safetylabaero.com &middot; Integrated aerospace safety analysis on the ARP 4761A / 4754B process.</p>`,
    `</footer>`,
    END,
  ].join("\n");
}

export function splice(html, block) {
  const a = html.indexOf(BEGIN), b = html.indexOf(END);
  if (a < 0 || b < 0) throw new Error("no SITE-FOOTER markers");
  return html.slice(0, a) + block + html.slice(b + END.length);
}

const isMain = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  const block = render(); const check = process.argv.includes("--check"); let bad = 0, wrote = 0;
  for (const f of PAGES) {
    const p = path.join(SITE, f);
    if (!fs.existsSync(p)) { console.log("missing page: " + f); bad++; continue; }
    const cur = fs.readFileSync(p, "utf8");
    let next;
    try { next = splice(cur, block); } catch (e) { console.log(f + ": " + e.message); bad++; continue; }
    if (next === cur) continue;
    if (check) { console.log(f + ": footer block is stale"); bad++; }
    else { fs.writeFileSync(p, next); wrote++; console.log("rewrote footer in " + f); }
  }
  if (check) { console.log(bad ? "footer check FAILED" : "footer check OK (" + PAGES.length + " pages)"); process.exit(bad ? 1 : 0); }
  console.log(wrote ? wrote + " page(s) updated" : "all footers current");
}
